server:
  port: 8768
spring:
  application:
    name: service-neo4j

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true