server:
  port: 8771
spring:
  application:
    name: service-dgraph

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true