server:
  port: 8770
spring:
  application:
    name: web-1
#设置静态文件路径css,js,图片等等
#  mvc:
#    static-path-pattern: /**
#  resources:
#    add-mappings: true
#springboot 页面热部署
spring.thymeleaf.cache: false