eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # 这只为prefer ip的话可以直接展示ip地址
  instance:
    prefer-ip-address: true
server:
  port: 8773
spring:
  application:
    name: kafka-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.129:9092
      binders:
        inputChannel:
          destination: test

